version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - mvn clean package
      - mkdir -p build
      - cp target/*.jar build/
      - cd build && zip lambda-deploy.zip *.jar && cd ..

artifacts:
  files:
    - build/lambda-deploy.zip